#include <map>
#include <string>
#include <vector>

#include "boost/date_time/gregorian/gregorian.hpp"

#include "snap.h"
#include "gtest/gtest.h"
#include "gmock/gmock.h"

TEST(generate_file_names, Default) {
  boost::gregorian::date from(2014,2,27);
  boost::gregorian::date to(2014,3,3);
  std::vector<std::string> file_names = snap::io::generate_file_names(from, to,
                                                                      "Data/",".txt");
  ASSERT_EQ(5,file_names.size());
  std::vector<std::string> expected_file_names{"Data/2014-02-27.txt",
      "Data/2014-02-28.txt",
      "Data/2014-03-01.txt",
      "Data/2014-03-02.txt",
      "Data/2014-03-03.txt"};   // inclusive search
  ASSERT_EQ(expected_file_names,
            file_names);
}

TEST(Program, Default) {
  snap::Program prog(R"ZZZ(Title: CBS News Sunday Morning
Description: Singer Sarah McLachlan; White House conversations secretly recorded by President Richard Nixon; director and screenwriter Richard Linklater; hoarding.
Channel: 3 - KYW
Recorded On: 7/27/2014 9:00:00 AM
Original Air Date: 7/27/2014
Transcript Generated by SnapStream
==================================

Captioning made possible by Johnson & Johnson, where quality products for the American family have been a tradition for generations good morning, I am Charles Osgood and this is Sunday morning. Summertime is the season when countless Americans spend as much time as possible outside the house, and no wonder. All too many of them, the house that they are escaping is a full house. A house so full of stuff there is hardly any room for them. Peter, Rita braver will report our cover story. .. 
>> Has now been diagnosed as a mental disorder, hoarding. >> Up to 5 percent of Americans. 
)ZZZ");
  ASSERT_EQ("CBS News Sunday Morning", prog.title);
  ASSERT_EQ("Singer Sarah McLachlan; White House conversations secretly recorded by President Richard Nixon; director and screenwriter Richard Linklater; hoarding.", prog.description);
  ASSERT_EQ("3 - KYW", prog.channel);
  ASSERT_EQ("2014-07-27", prog.recorded_date);
  ASSERT_EQ("2014-07-27", prog.aired_date);
  ASSERT_EQ("Captioning made possible by Johnson & Johnson, where quality products for the American family have been a tradition for generations good morning, I am Charles Osgood and this is Sunday morning. Summertime is the season when countless Americans spend as much time as possible outside the house, and no wonder. All too many of them, the house that they are escaping is a full house. A house so full of stuff there is hardly any room for them. Peter, Rita braver will report our cover story. .. \n>> Has now been diagnosed as a mental disorder, hoarding. >> Up to 5 percent of Americans.", prog.text);
  ASSERT_EQ("captioning made possible by johnson & johnson, where quality products for the american family have been a tradition for generations good morning, i am charles osgood and this is sunday morning. summertime is the season when countless americans spend as much time as possible outside the house, and no wonder. all too many of them, the house that they are escaping is a full house. a house so full of stuff there is hardly any room for them. peter, rita braver will report our cover story. .. \n>> has now been diagnosed as a mental disorder, hoarding. >> up to 5 percent of americans.", prog.lower_text);

  snap::Program equal_prog(R"ZZZ(Title: CBS News Sunday Morning
Description: Singer Sarah McLachlan; White House conversations secretly recorded by President Richard Nixon; director and screenwriter Richard Linklater; hoarding.
Channel: 3 - KYW
Recorded On: 7/27/2014 9:00:00 AM
Original Air Date: 7/27/2014
Transcript Generated by SnapStream
==================================

Captioning made possible by Johnson & Johnson, where quality products for the American family have been a tradition for generations good morning, I am Charles Osgood and this is Sunday morning. Summertime is the season when countless Americans spend as much time as possible outside the house, and no wonder. All too many of them, the house that they are escaping is a full house. A house so full of stuff there is hardly any room for them. Peter, Rita braver will report our cover story. .. 
>> Has now been diagnosed as a mental disorder, hoarding. >> Up to 5 percent of Americans. 
)ZZZ");
  snap::Program inequal_prog(R"ZZZ(Title: CBS News Sunday Morning
Description: Singer Sarah McLachlan; White House conversations secretly recorded by President Richard Nixon; director and screenwriter Richard Linklater; hoarding.
Channel: 3 - KYW
Recorded On: 7/27/2014 9:00:00 AM
Original Air Date: 7/27/2014
Transcript Generated by SnapStream
==================================

blah bal afas
)ZZZ");
  ASSERT_EQ(prog, equal_prog);
  ASSERT_NE(prog, inequal_prog);
}

TEST(parse_programs, Default) {
  std::string s(R"ZZZ(

ï»¿Title: ABC World News Now
Description: Global news.
Channel: 6 - WPVI
Recorded On: 7/23/2014 2:11:00 AM
Original Air Date: 1/5/1992
Transcript Generated by SnapStream
==================================

,,  going to make this place your home ?????? 

[2:14:16 AM]

>> It every time we come back singing from a break. 
>> Off good voice. 
They've earned their wings. And you can, too. Together we can solve child hunger. Support feeding America and your local food bank at feedingamerica.org.

ï»¿Title: Your World With Neil Cavuto
Description: Money tips from Wall Street.
Channel: 360 - FNC
Recorded On: 7/23/2014 4:00:00 PM
Original Air Date: 10/7/1996
Transcript Generated by SnapStream
==================================

Hero before it became passe and awful like Facebook. Maybe we'll have something old from the '80s like all of us. Dow no good. See you later.  life. Like a snapshot, snapped then shot over and done. And those of us still alive just watch and wonder about last week and this week and almost too afraid to even think about next week. )ZZZ");
  std::istringstream iss(s);  
  snap::Program prog0(R"ZZZ(Title: ABC World News Now
Description: Global news.
Channel: 6 - WPVI
Recorded On: 7/23/2014 2:11:00 AM
Original Air Date: 1/5/1992
Transcript Generated by SnapStream
==================================

,,  going to make this place your home ?????? 

[2:14:16 AM]

>> It every time we come back singing from a break. 
>> Off good voice. 
They've earned their wings. And you can, too. Together we can solve child hunger. Support feeding America and your local food bank at feedingamerica.org.
)ZZZ");
  snap::Program prog1(R"ZZZ(Title: Your World With Neil Cavuto
Description: Money tips from Wall Street.
Channel: 360 - FNC
Recorded On: 7/23/2014 4:00:00 PM
Original Air Date: 10/7/1996
Transcript Generated by SnapStream
==================================

Hero before it became passe and awful like Facebook. Maybe we'll have something old from the '80s like all of us. Dow no good. See you later.  life. Like a snapshot, snapped then shot over and done. And those of us still alive just watch and wonder about last week and this week and almost too afraid to even think about next week. )ZZZ");
  std::vector<snap::Program> prog_vector = snap::io::parse_programs(iss);
  ASSERT_EQ(prog_vector.size(), 2);
  ASSERT_EQ(prog0, prog_vector[0]);
  ASSERT_EQ(prog1, prog_vector[1]);
}

TEST(read_dictionary, Default) {
  std::string s = R"ZZZ(Afghanistan,{afghan*},AFG,Country
Akrotiri and Dhekelia,{akrotiri} + {dhekelia},AKD,Country
Albania,{albania*},ALB,Country
Algeria,{algeria*},ALG,Country
Andorra,{andorra*},AND,Country
Angola,{angola*},AGO,Country
Anguilla,{anguilla*},AGU,Country
Antarctica,{antarctica},ATC,Country
Antigua and Barbuda,{antigua} + {barbuda},AAB,Country
Argentina,{argentina} + {argentine} + {argentinian},ARG,Country
Armenia,{armenia},ARM,Country
Aruba,{aruba},ARU,Country
Ashmore and Cartier Islands,{ashmore and cartier islands},ACI,Country
Australia,{australia},AUL,Country
Austria,{austria},AUT,Country
Azerbaijan,{azerbaijan},AZB,Country
Bahamas,{bahamas},BHM,Country
Bahrain,{bahrain},BHR,Country
Bangladesh,{bangladesh*},BAN,Country
Barbados,{barbados},BAR,Country
Bassas da India,{bassas da india},BDI,Country
Belarus,{belarus},BLR,Country
Belgium,{belgium} + {belgian} !@ {waffles},BLG,Country
Belize,{belize},BLZ,Country
Benin,{benin},BEN,Country)ZZZ";
  std::istringstream iss(s);
  std::map<std::string, std::tuple<std::string, std::string, std::string>> dict = snap::io::read_dictionary(iss);
  
  ASSERT_EQ("AFG", std::get<0>(dict["{afghan*}"]));
  ASSERT_EQ("Afghanistan", std::get<1>(dict["{afghan*}"]));
  ASSERT_EQ("Country", std::get<2>(dict["{afghan*}"]));
  ASSERT_EQ("BEN", std::get<0>(dict["{benin}"]));
  ASSERT_EQ("Benin", std::get<1>(dict["{benin}"]));
  ASSERT_EQ("Country", std::get<2>(dict["{benin}"]));
}

TEST(Program, timestamps) {
  snap::Program prog(R"ZZZ(Title: The Voice - The Battles, Part 3
Description: Advisers John Fogerty, Brad Paisley, Selena Gomez, and Missy Elliott help the coaches with their teams; the contestants participate in the battle rounds.
Channel: 10 - WCAU
Recorded On: 10/19/2015 8:00:00 PM
Original Air Date: 10/19/2015
Transcript Generated by SnapStream
==================================

 
Lyndsey: This is my chance to prove that I do have what it takes to make a successful career in this industry. 
Evan: I don't want it to end yet, I want to keep doing this, so I'm singing with everything I've got today. 
Daly: Tonight, the battles continue. 
Pharrell: This is, like, the big leagues. This is where the best voices in America end up. Holy crap. Hey! 
Daly: To help prepare their artists, our coaches enlisted help from some of the biggest names in music. Oh, this is gonna be fun. It just sounded raspy. I love a raspy voice. Did you guys just go out on the road for a week or something and come back here? 
[ Laughter ] That's amazing. You make great eye contact. And maybe just have a moment where you look at her genuinely. 
?????? Everyo-o-o-ne  there's so much more than just singing a song. It's commanding the presence of the stage. 
?????? Kind of music just soothes the soul  
Daly: Our artists will be pushed like never before to remain on their teams...   Days of old ?????? 
?????? yeah, we like that old time rock 'N' roll ?????? I freakin' love the sound of your voice. ...And our coaches each have only one steal left. 
Gwen: My team's still gonna evolve and change, and I do have my eye on a few people. 

[8:02:08 PM]

Hopefully I can steal. 
?????? I'll go wherever you will go  
Daly: It's the most unforgettable night of battles yet. 
-I'm seriously getting pissed off. -Whoa. There was something really, like, brawly and, like, unruly about what was happening up there. 
-Please let me borrow that cane for a second... 
-Yeah, here you go, man. ...So I can go beat the hell out of Adam with it. Man. [ Cheers and applause ] 
Daly: The battles start right now. Welcome to universal studios Hollywood, where our coaches are getting ready for night 3 of the battles. 
Adam: I'm excited. I have one steal left in case you wanted to know. I have one steal left, and I'm excited. 
-I have one left. -Pharrell, one? So one, one, one, one? Ooh, it's gonna be a bloodbath. Let's do this. [ Chuckles ] 
Daly: As they get settled, let's meet Blake's first battle pairing -- 24-year-old Blaine Mitchell from Fort Worth, Texas, versus 33-year-old blind Joe from Fargo, North Dakota. Blaine Mitchell, a former athlete, came to "The voice" in order to take his music career to the next level. I blew out my knee, so the MLB said, "Bye-bye." That became the moment that I was like, "Okay, I'm gonna put all of my efforts into my band with my brother." 
?????? Tell me, did Venus blow your mind?  
Daly: During his blind audition, he got the attention of both Gwen and Blake. Your strength and your voice, it was incredible. You started hitting some notes. That one that you hit, and you just held for a long time... I'm a fan, dude. I got to go with Blake. Yes! 
Daly: Blind Joe refused to let anything stop him from achieving his dreams. 
Joe: I was born three months premature, and my retinas didn't attach. My mom and dad really instilled that if you want something, you've got to work hard. So, yeah, this is a truly blind audition. 
[ Laughs ] 
?????? Never woulda loaded up my .44  
Daly: His powerful performance got all four coaches to push their buttons. There was something so honest about it. It's so beautiful. There's only one blind Joe in the freakin' world. I pick Blake. Yes! 
Blake: Blaine, blind Joe. 
-Hey, brother. -Hey! 

[8:04:09 AM]

This is my friend Brad paisley right here. 
-Hi, Joe. How are Ya? -Good, man. How are you? Anybody that knows country music knows Brad paisley. He is an amazing guitarist. Guy is a living legend. It's like a dream come true for a north woods country boy. You guys have big, loud voices with power and energy behind what you both do. You guys are two, like, dudes that leave blood and guts up there. 
-Yeah. -And that's why you two are doing it. "Old time rock and roll" by Bob Seger -- I mean, country singers sing it, rock guys sing it. It's just kind of a universal song. 
-Blaine pinned us back in our seats here. 
-[ Chuckles ] 
-But I felt like you had trouble hitting the pitches. -Right. 
-Blind Joe, do I call you "Blind Joe"? -Yeah. Be like me, "Hey, fat Blake." 
-You know what I mean? -[ Laughs ] Everybody back home calls me blind Joe. Okay, there's places in that chorus where the melody changes. You can go up. If you do that the right way, it makes for great music. 
-Yeah, yeah. -Yeah. Blaine has that quality in his voice with the higher notes that he can just punch them out. ??? Don't try to take me to a disco ?????? so I really need to up my game a little bit. 
-You guys just have to give this... -Yeah. ...Everything you got from the moment the song starts. 
-Yes, sir. -You know, that's just the nature of this song. 
-Yeah. -And that's why you two are doing it... 
-...Because that's what you do. -Yeah. I also think lay off a little bit 
-right before going for the high note. -Yeah. 
-Leave some gas in the tank. -Yeah. 
-Yeah, yeah. -Boom. It's good. 
Daly: As their battle nears, Blaine and blind Joe meet with Blake and Brad paisley for their final rehearsal. I'm going high. 
?????? That old time rock 'N' roll  
-Blaine, I think you should rock out like you normally would. -Sweet. It's a front-man thing, and we wish we could move like that. 
-Oh, my gosh. -The way you do the Mike thing and all that. 

[12:06:10 PM]

This is just you guys on stage, sweaty, with beer and girls everywhere, and just 
-- 
[ laughs ] Jack Daniels in the glass? Yes. All of that. That's what this moment is.)ZZZ");
std::string expected(R"ZZZ(Lyndsey: This is my chance to prove that I do have what it takes to make a successful career in this industry. 
Evan: I don't want it to end yet, I want to keep doing this, so I'm singing with everything I've got today. 
Daly: Tonight, the battles continue. 
Pharrell: This is, like, the big leagues. This is where the best voices in America end up. Holy crap. Hey! 
Daly: To help prepare their artists, our coaches enlisted help from some of the biggest names in music. Oh, this is gonna be fun. It just sounded raspy. I love a raspy voice. Did you guys just go out on the road for a week or something and come back here? 
[ Laughter ] That's amazing. You make great eye contact. And maybe just have a moment where you look at her genuinely. 
?????? Everyo-o-o-ne  there's so much more than just singing a song. It's commanding the presence of the stage. 
?????? Kind of music just soothes the soul  
Daly: Our artists will be pushed like never before to remain on their teams...   Days of old ?????? 
?????? yeah, we like that old time rock 'N' roll ?????? I freakin' love the sound of your voice. ...And our coaches each have only one steal left. 
Gwen: My team's still gonna evolve and change, and I do have my eye on a few people. Hopefully I can steal. 
?????? I'll go wherever you will go  
Daly: It's the most unforgettable night of battles yet. 
-I'm seriously getting pissed off. -Whoa. There was something really, like, brawly and, like, unruly about what was happening up there. 
-Please let me borrow that cane for a second... 
-Yeah, here you go, man. ...So I can go beat the hell out of Adam with it. Man. [ Cheers and applause ] 
Daly: The battles start right now. Welcome to universal studios Hollywood, where our coaches are getting ready for night 3 of the battles. 
Adam: I'm excited. I have one steal left in case you wanted to know. I have one steal left, and I'm excited. 
-I have one left. -Pharrell, one? So one, one, one, one? Ooh, it's gonna be a bloodbath. Let's do this. [ Chuckles ] 
Daly: As they get settled, let's meet Blake's first battle pairing -- 24-year-old Blaine Mitchell from Fort Worth, Texas, versus 33-year-old blind Joe from Fargo, North Dakota. Blaine Mitchell, a former athlete, came to "The voice" in order to take his music career to the next level. I blew out my knee, so the MLB said, "Bye-bye." That became the moment that I was like, "Okay, I'm gonna put all of my efforts into my band with my brother." 
?????? Tell me, did Venus blow your mind?  
Daly: During his blind audition, he got the attention of both Gwen and Blake. Your strength and your voice, it was incredible. You started hitting some notes. That one that you hit, and you just held for a long time... I'm a fan, dude. I got to go with Blake. Yes! 
Daly: Blind Joe refused to let anything stop him from achieving his dreams. 
Joe: I was born three months premature, and my retinas didn't attach. My mom and dad really instilled that if you want something, you've got to work hard. So, yeah, this is a truly blind audition. 
[ Laughs ] 
?????? Never woulda loaded up my .44  
Daly: His powerful performance got all four coaches to push their buttons. There was something so honest about it. It's so beautiful. There's only one blind Joe in the freakin' world. I pick Blake. Yes! 
Blake: Blaine, blind Joe. 
-Hey, brother. -Hey! This is my friend Brad paisley right here. 
-Hi, Joe. How are Ya? -Good, man. How are you? Anybody that knows country music knows Brad paisley. He is an amazing guitarist. Guy is a living legend. It's like a dream come true for a north woods country boy. You guys have big, loud voices with power and energy behind what you both do. You guys are two, like, dudes that leave blood and guts up there. 
-Yeah. -And that's why you two are doing it. "Old time rock and roll" by Bob Seger -- I mean, country singers sing it, rock guys sing it. It's just kind of a universal song. 
-Blaine pinned us back in our seats here. 
-[ Chuckles ] 
-But I felt like you had trouble hitting the pitches. -Right. 
-Blind Joe, do I call you "Blind Joe"? -Yeah. Be like me, "Hey, fat Blake." 
-You know what I mean? -[ Laughs ] Everybody back home calls me blind Joe. Okay, there's places in that chorus where the melody changes. You can go up. If you do that the right way, it makes for great music. 
-Yeah, yeah. -Yeah. Blaine has that quality in his voice with the higher notes that he can just punch them out. ??? Don't try to take me to a disco ?????? so I really need to up my game a little bit. 
-You guys just have to give this... -Yeah. ...Everything you got from the moment the song starts. 
-Yes, sir. -You know, that's just the nature of this song. 
-Yeah. -And that's why you two are doing it... 
-...Because that's what you do. -Yeah. I also think lay off a little bit 
-right before going for the high note. -Yeah. 
-Leave some gas in the tank. -Yeah. 
-Yeah, yeah. -Boom. It's good. 
Daly: As their battle nears, Blaine and blind Joe meet with Blake and Brad paisley for their final rehearsal. I'm going high. 
?????? That old time rock 'N' roll  
-Blaine, I think you should rock out like you normally would. -Sweet. It's a front-man thing, and we wish we could move like that. 
-Oh, my gosh. -The way you do the Mike thing and all that. This is just you guys on stage, sweaty, with beer and girls everywhere, and just 
-- 
[ laughs ] Jack Daniels in the glass? Yes. All of that. That's what this moment is.)ZZZ");
  ASSERT_EQ(expected, prog.text);
}

int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();    
}
